# reg-db.zsh — the register inventory and its metadata database.
#
# The ssh config block (generated by scripts/gen_ssh_registers.py) is the
# inventory: it decides which registers exist. The sqlite database only
# decorates them, and nothing about its schema is guaranteed, so everything
# here discovers tables/columns instead of assuming them (pin with
# REG_DB_TABLE / REG_DB_HOST_COL / REG_DB_IP_COL / REG_DB_STORE_*).
_REG_CONF="${REG_CONF:-$HOME/.ssh/conf.d/registers}"
_REG_DB="${REG_DB:-$HOME/store_registers.db}"

_reg_hosts() {
    if [[ ! -f $_REG_CONF ]]; then
        print -u2 "no register inventory at $_REG_CONF"
        print -u2 "generate it: scripts/gen_ssh_registers.py --db <db> --user <user>"
        return 1
    fi
    awk '/^Host / && $2 !~ /[?*]/ {print $2}' "$_REG_CONF"
}

# Find the table and columns that hold hostnames and IPs, printed as
# "table<TAB>hostcol<TAB>ipcol". Nothing about the inventory db's schema is
# guaranteed — the name "registers" was inherited from gen_ssh_registers.py and
# is not always right — so discover it instead of assuming, and let the user
# pin it with REG_DB_TABLE / REG_DB_HOST_COL / REG_DB_IP_COL.
_reg_db_schema() {
    if [[ -n $REG_DB_TABLE && -n $REG_DB_HOST_COL ]]; then
        print -r -- "${REG_DB_TABLE}"$'\t'"${REG_DB_HOST_COL}"$'\t'"${REG_DB_IP_COL:-}"
        return 0
    fi

    local -a tables cols
    local t hostc ipc c
    tables=(${(f)"$(sqlite3 -readonly "$_REG_DB" \
        "SELECT name FROM sqlite_master WHERE type IN ('table','view');" 2>/dev/null)"})

    for t in $tables; do
        cols=(${(f)"$(sqlite3 -readonly "$_REG_DB" "PRAGMA table_info('$t');" 2>/dev/null \
            | awk -F'|' '{print $2}')"})
        (( ${#cols} )) || continue

        # Prefer the most specific name, then anything host-ish.
        hostc=""
        for c in register_hostname hostname host_name host; do
            (( ${cols[(I)$c]} )) && { hostc=$c; break }
        done
        [[ -n $hostc ]] || for c in $cols; do
            [[ ${c:l} == *host* ]] && { hostc=$c; break }
        done
        [[ -n $hostc ]] || continue

        ipc=""
        for c in register_ip ip_address ipaddress ip addr; do
            (( ${cols[(I)$c]} )) && { ipc=$c; break }
        done
        [[ -n $ipc ]] || for c in $cols; do
            [[ ${c:l} == *ip* ]] && { ipc=$c; break }
        done

        print -r -- "$t"$'\t'"$hostc"$'\t'"$ipc"
        return 0
    done
    return 1
}

# Find the store table and the column holding the store number, as
# "table<TAB>keycol". Registers are named NNNNregNN, so the first four
# characters are the store number — the same derivation gen_ssh_registers.py
# uses to join. Pin with REG_DB_STORE_TABLE / REG_DB_STORE_COL.
_reg_db_store() {
    if [[ -n $REG_DB_STORE_TABLE && -n $REG_DB_STORE_COL ]]; then
        print -r -- "${REG_DB_STORE_TABLE}"$'\t'"${REG_DB_STORE_COL}"
        return 0
    fi

    local regtbl schema
    schema=$(_reg_db_schema) && regtbl=${schema%%$'\t'*}

    local -a tables cols
    local t c keyc
    tables=(${(f)"$(sqlite3 -readonly "$_REG_DB" \
        "SELECT name FROM sqlite_master WHERE type IN ('table','view');" 2>/dev/null)"})

    for t in $tables; do
        [[ $t == $regtbl ]] && continue          # the register table is not the store table
        cols=(${(f)"$(sqlite3 -readonly "$_REG_DB" "PRAGMA table_info('$t');" 2>/dev/null \
            | awk -F'|' '{print $2}')"})
        keyc=""
        for c in store_number store_num storenumber store_id store; do
            (( ${cols[(I)$c]} )) && { keyc=$c; break }
        done
        [[ -n $keyc ]] && { print -r -- "$t"$'\t'"$keyc"; return 0 }
    done
    return 1
}

_reg_db_cols() {
    sqlite3 -readonly "$_REG_DB" "PRAGMA table_info('$1');" 2>/dev/null | awk -F'|' '{print $2}'
}

_reg_db_has_col() {
    local -a cols; cols=(${(f)"$(_reg_db_cols "$1")"})
    (( ${cols[(I)$2]} ))
}

# A quoted, comma-separated column list for <table>, minus bookkeeping columns
# nobody wants staring at them in a preview pane. Still schema-agnostic: it
# names what to *hide*, never what to show.
_reg_db_sel() {
    local c out=""
    local -a skip=(id rowid sync_lock last_updated)
    for c in ${(f)"$(_reg_db_cols "$1")"}; do
        (( ${skip[(Ie)${c:l}]} )) && continue
        out+="${out:+, }\\\"$c\\\""
    done
    [[ -n $out ]] || return 1
    print -r -- "$out"
}

# "stbl<TAB>skey<TAB>joincond" for joining the store table (as s) onto register
# rows (as r): prefer a real foreign key on the register table; else derive the
# store from the hostname's 4-char prefix — the NNNNregNN naming, the same
# derivation gen_ssh_registers.py uses. One place owns that decision so
# _reg_meta and _reg_meta_full can never disagree on it.
_reg_db_store_join() {
    local tbl="$1" hostc="$2" sschema stbl skey cond
    sschema=$(_reg_db_store) || return 1
    stbl=${sschema%%$'\t'*}
    skey=${sschema##*$'\t'}
    if _reg_db_has_col "$tbl" "$skey"; then
        cond="s.\"$skey\" = r.\"$skey\""
    else
        cond="s.\"$skey\" = substr(r.\"$hostc\", 1, 4)"
    fi
    print -r -- "$stbl"$'\t'"$skey"$'\t'"$cond"
}

# "hostname<TAB>store<TAB>city<TAB>state<TAB>regional" for every register in the
# database, using whichever of those columns actually exist. Fails when there is
# no usable database, so callers fall back to bare hostnames.
_reg_meta() {
    [[ -f $_REG_DB ]] || return 1
    command -v sqlite3 >/dev/null 2>&1 || return 1

    local schema tbl hostc sj stbl cond
    schema=$(_reg_db_schema) || return 1
    tbl=${schema%%$'\t'*}
    hostc=${${schema#*$'\t'}%%$'\t'*}
    sj=$(_reg_db_store_join "$tbl" "$hostc") || return 1
    stbl=${sj%%$'\t'*}
    cond=${sj##*$'\t'}

    # Display columns, in order, skipping any this schema does not have.
    local c
    local -a want=(store_number store_city store_state store_regional) cols=()
    for c in $want; do
        _reg_db_has_col "$stbl" "$c" && cols+=("s.\"$c\"")
    done
    (( ${#cols} )) || return 1

    sqlite3 -readonly -separator $'\t' "$_REG_DB" \
        "SELECT r.\"$hostc\", ${(j:, :)cols} FROM \"$tbl\" r
         LEFT JOIN \"$stbl\" s ON $cond;" 2>/dev/null
}

# Like _reg_meta, but one row per register with the IP included, for consumers
# that build their own join/output rather than the aligned picker rows:
#   host<TAB>ip<TAB>store<TAB>city<TAB>state<TAB>regional
# Empty string for any column the schema lacks. Used by the Alfred script filter
# (mac/alfred/reg-filter.zsh) and the RoyalJSON generator (mac/royaltsx/). Same
# discovery primitives as _reg_meta; the IP lets the target be an address when
# /etc/hosts is not set up.
_reg_meta_full() {
    [[ -f $_REG_DB ]] && command -v sqlite3 >/dev/null 2>&1 || return 1
    local schema tbl hostc ipc
    schema=$(_reg_db_schema) || return 1
    tbl=${schema%%$'\t'*}
    hostc=${${schema#*$'\t'}%%$'\t'*}
    ipc=${schema##*$'\t'}

    local -a sel=("r.\"$hostc\"")
    sel+=("${ipc:+r.\"$ipc\"}"); [[ -n $ipc ]] || sel[-1]="''"

    local c sj stbl join=""
    local -a scols=(store_number store_city store_state store_regional)
    if sj=$(_reg_db_store_join "$tbl" "$hostc"); then
        stbl=${sj%%$'\t'*}
        for c in $scols; do
            if _reg_db_has_col "$stbl" "$c"; then sel+=("s.\"$c\""); else sel+=("''"); fi
        done
        join="LEFT JOIN \"$stbl\" s ON ${sj##*$'\t'}"
    else
        sel+=("''" "''" "''" "''")
    fi

    sqlite3 -readonly -separator $'\t' "$_REG_DB" \
        "SELECT ${(j:, :)sel} FROM \"$tbl\" r $join;" 2>/dev/null
}

