#!/usr/bin/env python3
"""
gen_ssh_registers.py - generate an SSH config Include file that maps
register hostnames (NNNNregNN) to their IPs, so they can be reached
through the store gateway by name without any DNS.

Reads store_registers.db, joins registers to stores by the 4-char store
prefix (same derivation as the Ansible inventory plugin), excludes stores
explicitly marked invalid (keeps not-yet-open stores), and writes
~/.ssh/conf.d/registers.

Stdlib only. Python 3.6+ compatible.
"""

import argparse
import os
import shutil
import sqlite3
import sys
from datetime import datetime
from pathlib import Path

# --- Schema mapping: adjust if your column names differ -----------------
REGISTERS_TABLE = "registers"
STORES_TABLE    = "stores"
COL_HOSTNAME    = "register_hostname"       # registers: "0999reg01"
COL_IP          = "register_ip"     # registers: "172.20.4.11"
COL_STORE_NUM   = "store_number"   # stores:    "0999"
COL_STORE_VALID = "store_valid"    # stores:    'Y' / 'N'

MARK_BEGIN = "# >>> gen_ssh_registers include >>>"
MARK_END   = "# <<< gen_ssh_registers include <<<"

SSH_DEFAULT_OUT = str(Path.home() / ".ssh" / "conf.d" / "registers")

HOSTS_BEGIN = "# >>> gen_ssh_registers hosts >>>"
HOSTS_END   = "# <<< gen_ssh_registers hosts <<<"


def parse_args(argv=None):
    p = argparse.ArgumentParser(
        description="Generate an SSH config Include file for POS registers.")
    p.add_argument("--db", default="store_registers.db",
                   help="Path to store_registers.db (default: ./store_registers.db)")
    p.add_argument("--format", choices=("ssh", "hosts"), default="ssh",
                   help="ssh: an SSH config Include file (default). "
                        "hosts: an /etc/hosts block, so apps that do not read "
                        "~/.ssh/config (Royal TSX) can reach registers by name")
    p.add_argument("--user",
                   help="Login user for registers (sets User in the wildcard "
                        "block). Required for --format ssh; ignored for hosts")
    p.add_argument("--hosts-file", default="/etc/hosts",
                   help="Target for --install-hosts (default: /etc/hosts)")
    p.add_argument("--install-hosts", action="store_true",
                   help="Merge the generated block into --hosts-file, replacing "
                        "any previous block. Needs write access: run under sudo")
    p.add_argument("--jump", default="lassssgate01.traderjoes.com",
                   help="ProxyJump gateway host")
    p.add_argument("--term", default="xterm-256color",
                   help="Pin TERM for register sessions via SetEnv (default: "
                        "xterm-256color; pass '' to disable). Fixes garbled "
                        "output when the remote lacks the xterm-ghostty "
                        "terminfo. Needs OpenSSH 8.7+ on the client.")
    p.add_argument("--out", default=SSH_DEFAULT_OUT,
                   help="Output file (ssh format default: ~/.ssh/conf.d/registers)")
    p.add_argument("--no-control-master", action="store_true",
                   help="Omit connection-multiplexing options (e.g. Windows OpenSSH)")
    p.add_argument("--install-include", action="store_true",
                   help="Insert an Include line into ~/.ssh/config ahead of any 'Host *' block")
    p.add_argument("--dry-run", action="store_true",
                   help="Print generated config to stdout instead of writing")
    p.add_argument("-y", "--yes", action="store_true",
                   help="Skip confirmation prompt when editing ~/.ssh/config")
    return p.parse_args(argv)


def fetch_registers(db_path):
    if not os.path.exists(db_path):
        sys.exit("error: database not found: {}".format(db_path))
    con = sqlite3.connect("file:{}?mode=ro".format(db_path), uri=True)
    con.row_factory = sqlite3.Row
    sql = """
        SELECT r.{host} AS hostname, r.{ip} AS ip
        FROM {regs} r
        LEFT JOIN {stores} s
          ON substr(r.{host}, 1, 4) = s.{snum}
        WHERE IFNULL(s.{valid}, 'Y') <> 'N'
          AND r.{ip} IS NOT NULL
          AND TRIM(r.{ip}) <> ''
        ORDER BY r.{host}
    """.format(host=COL_HOSTNAME, ip=COL_IP, regs=REGISTERS_TABLE,
               stores=STORES_TABLE, snum=COL_STORE_NUM, valid=COL_STORE_VALID)
    try:
        rows = con.execute(sql).fetchall()
    except sqlite3.OperationalError as e:
        sys.exit("error: query failed ({}). Check the schema mapping "
                 "constants at the top of this script.".format(e))
    finally:
        con.close()
    seen = {}
    for row in rows:
        h = row["hostname"]
        if h and h not in seen:        # de-dupe, first wins
            seen[h] = row["ip"]
    return seen


def build_config(hosts, args):
    ts = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    out = []
    out.append("# === TJ registers - generated by gen_ssh_registers.py ===")
    out.append("# Source: {} | {} | {} hosts".format(
        os.path.basename(args.db), ts, len(hosts)))
    out.append("# Do not hand-edit; rerun the generator.")
    out.append("")
    out.append("Host ????reg??")
    out.append("    ProxyJump            {}".format(args.jump))
    out.append("    User                 {}".format(args.user))
    out.append("    StrictHostKeyChecking no")
    out.append("    UserKnownHostsFile   /dev/null")
    out.append("    LogLevel             ERROR")
    out.append("    ServerAliveInterval  30")
    if args.term:
        out.append("    SetEnv               TERM={}".format(args.term))
    if not args.no_control_master:
        out.append("    ControlMaster        auto")
        out.append("    ControlPath          ~/.ssh/cm/%C")
        out.append("    ControlPersist       60s")
    out.append("")
    for host in sorted(hosts):
        out.append("Host {}".format(host))
        out.append("    HostName {}".format(hosts[host]))
    out.append("")
    return "\n".join(out)


def build_hosts(hosts, args):
    """An /etc/hosts block. Royal TSX and friends do not read ~/.ssh/config, so
    without this they can only be given a bare IP -- which is also all their tab
    titles can show."""
    ts = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    width = max(len(ip) for ip in hosts.values())
    out = [HOSTS_BEGIN,
           "# TJ registers - generated by gen_ssh_registers.py",
           "# Source: {} | {} | {} hosts".format(
               os.path.basename(args.db), ts, len(hosts)),
           "# Do not hand-edit; rerun the generator."]
    for host in sorted(hosts):
        out.append("{:<{w}}  {}".format(hosts[host], host, w=width))
    out.append(HOSTS_END)
    return "\n".join(out) + "\n"


def install_hosts(hosts_path, block, assume_yes):
    """Replace our marked block in hosts_path, leaving every other line alone."""
    hosts_path = Path(hosts_path)
    text = hosts_path.read_text() if hosts_path.exists() else ""
    lines = text.splitlines()

    if HOSTS_BEGIN in lines and HOSTS_END in lines:
        start = lines.index(HOSTS_BEGIN)
        end = lines.index(HOSTS_END, start)
        before, after = lines[:start], lines[end + 1:]
        verb, prompt_verb = "Replaced", "Replace"
    elif HOSTS_BEGIN in lines or HOSTS_END in lines:
        sys.exit("error: {} has only one of the two markers; fix it by hand"
                 .format(hosts_path))
    else:
        before, after = lines, []
        verb, prompt_verb = "Added", "Add"

    # A register name already mapped outside our block would shadow, or be
    # shadowed by, the block. Say so rather than quietly producing two entries.
    names = {ln.split()[1] for ln in block.splitlines()
             if ln and not ln.startswith("#") and len(ln.split()) > 1}
    clashes = sorted(
        n for ln in (before + after)
        if ln.strip() and not ln.lstrip().startswith("#")
        for n in ln.split()[1:] if n in names)
    if clashes:
        sys.stderr.write("warning: already in {} outside our block: {}\n".format(
            hosts_path, ", ".join(clashes[:5]) + ("..." if len(clashes) > 5 else "")))

    if not assume_yes:
        ans = input("{} the register block in {}? [y/N] ".format(
            prompt_verb, hosts_path)).strip().lower()
        if ans not in ("y", "yes"):
            print("Skipped editing {}.".format(hosts_path))
            return

    if hosts_path.exists():
        backup = "{}.bak.{}".format(hosts_path,
                                    datetime.now().strftime("%Y%m%d%H%M%S"))
        shutil.copy2(str(hosts_path), backup)
        print("Backed up {} -> {}".format(hosts_path, backup))

    while before and not before[-1].strip():
        before.pop()
    new_lines = before + ([""] if before else []) + block.splitlines() + after
    try:
        hosts_path.write_text("\n".join(new_lines) + "\n")
    except PermissionError:
        sys.exit("error: cannot write {} -- rerun under sudo".format(hosts_path))
    # Deliberately no chmod: /etc/hosts is world-readable and must stay that way.
    print("{} the register block in {}.".format(verb, hosts_path))


def install_include(config_path, include_target, assume_yes):
    config_path = Path(config_path)
    text = config_path.read_text() if config_path.exists() else ""
    if "Include {}".format(include_target) in text:
        print("Include already present in {}.".format(config_path))
        return
    if not assume_yes:
        ans = input("Edit {} to add the Include line? [y/N] ".format(
            config_path)).strip().lower()
        if ans not in ("y", "yes"):
            print("Skipped editing {}.".format(config_path))
            return
    if config_path.exists():
        backup = "{}.bak.{}".format(config_path,
                                    datetime.now().strftime("%Y%m%d%H%M%S"))
        shutil.copy2(str(config_path), backup)
        print("Backed up {} -> {}".format(config_path, backup))
    block = [MARK_BEGIN, "Include {}".format(include_target), MARK_END]
    lines = text.splitlines()
    idx = None
    for i, ln in enumerate(lines):
        if ln.strip().lower().startswith("host "):
            idx = i
            break
    if idx is None:
        new_lines = lines + ([""] if lines else []) + block
    else:
        new_lines = lines[:idx] + block + [""] + lines[idx:]
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text("\n".join(new_lines) + "\n")
    try:
        os.chmod(str(config_path), 0o600)
    except OSError:
        pass
    print("Inserted Include into {}.".format(config_path))


def main():
    args = parse_args()
    if args.format == "ssh" and not args.user:
        sys.exit("error: --user is required for --format ssh")

    hosts = fetch_registers(args.db)
    if not hosts:
        sys.exit("error: no registers matched. Check filters / schema mapping.")

    if args.format == "hosts":
        block = build_hosts(hosts, args)
        if args.install_hosts:
            install_hosts(args.hosts_file, block, args.yes)
            return
        if args.dry_run or args.out == SSH_DEFAULT_OUT:
            # No --out given (it still holds the ssh default), so print instead
            # of writing an /etc/hosts block into ~/.ssh/conf.d.
            sys.stdout.write(block)
            sys.stderr.write("# {} hosts (nothing written; use --install-hosts "
                             "or --out)\n".format(len(hosts)))
            return
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(block)
        print("Wrote {} ({} hosts).".format(out_path, len(hosts)))
        return

    config_text = build_config(hosts, args)

    if args.dry_run:
        print(config_text)
        sys.stderr.write("# {} hosts (dry run, nothing written)\n".format(len(hosts)))
        return

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if not args.no_control_master:
        (Path.home() / ".ssh" / "cm").mkdir(parents=True, exist_ok=True)
    out_path.write_text(config_text)
    try:
        os.chmod(str(out_path), 0o600)
    except OSError:
        pass
    print("Wrote {} ({} hosts).".format(out_path, len(hosts)))

    if args.install_include:
        ssh_dir = Path.home() / ".ssh"
        try:
            include_target = str(out_path.relative_to(ssh_dir))
        except ValueError:
            include_target = str(out_path)
        install_include(ssh_dir / "config", include_target, args.yes)


if __name__ == "__main__":
    main()